type Person {
  id: ID!
  name: String!
}

type PeopleConnection {
  items: [Person!]!
  nextToken: String
}

type Query {
  person(id: ID!): Person
  people(nextToken: String): PeopleConnection
}

type Mutation {
  createPerson(name: String!): Person!
}

schema {
  query: Query
  mutation: Mutation
}
